luku1 = int(input("Anna luku 1: "))
luku2 = int(input("Anna luku 2: "))
luku3 = int(input("Anna luku 3: "))
print(f"Lukujen summa: {luku1+luku2+luku3}")
print(f"Lukujen tulo: {luku1*luku2*luku3}")
print(f"Lukujen keskiarvo: {(luku1+luku2+luku3)/3}")